In [10]:
#numpy

In [9]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)


1.20.1


In [5]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [6]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(" No of dimensions : ", arr.ndim)    

[[[[[1 2 3 4]]]]]
 No of dimensions :  5


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2])

3


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [17]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element on first row = ", arr[0, 1])

2nd element on first row =  2


In [3]:
import numpy as np
arr4 = np.array([[[1, 2, 3], [1,2 ,3]], [[1, 2, 3], [1,2,3]]])
print(arr4[1,1,2])

3


In [4]:
import numpy as np
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5[1, -1])

6


In [6]:
import numpy as np
arr6 = np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
print(arr6[1:5])
print(arr6[-4:-1])

[2 3 4 5]
[6 7 8]


In [7]:
import numpy as np
print(arr5[1, 1:3])

[5 6]


In [8]:
import numpy as np
print(arr5[0:2, 2])

[3 6]


In [9]:
import numpy as np
x = arr6.copy()
y = arr6.view()
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [10]:
import numpy as np
print(arr5.shape)

(2, 3)


In [11]:
import numpy as np
reshapedArr6 = arr6.reshape(3,3)
print(reshapedArr6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
import numpy as np
arr=np.array([1,2,3,4,5])
concArr = np.concatenate((arr, arr6))
print(concArr)

[1 2 3 4 5 1 2 3 4 5 6 7 8 9]


In [20]:
concArr = np.concatenate((arr, arr6))
print(concArr)

[1 2 3 4 5 1 2 3 4 5 6 7 8 9]


In [22]:
arr3 = np.array([[[1, 2, 3], [1,2 ,3]], [[1, 2, 3], [1,2,3]]])
concArr2D = np.concatenate((arr4, arr3))

print(concArr2D)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [23]:
splitArr = np.array_split(concArr2D, 4)
print(splitArr)

[array([[[1, 2, 3],
        [1, 2, 3]]]), array([[[1, 2, 3],
        [1, 2, 3]]]), array([[[1, 2, 3],
        [1, 2, 3]]]), array([[[1, 2, 3],
        [1, 2, 3]]])]


In [24]:
print(np.sort(arr6))

[1 2 3 4 5 6 7 8 9]
